export const supportedReadApiEndpoints = [
  "/health",
  "/meta/capabilities",
  "/auth/x/start",
  "/auth/x/callback",
  "/auth/x/pending/:linkToken",
  "/auth/x/finalize",
  "/meta/contracts",
  "/meta/external",
  "/meta/diagnostics",
  "/meta/rpc",
  "/meta/rewards",
  "/meta/playbook",
  "/meta/playbook/:sectionId",
  "/agent/bootstrap",
  "/agent/tx-intent",
  "/agent/world-rules",
  "/agent/characters/:owner",
  "/agent/state/:characterId",
  "/agent/session-state/:characterId",
  "/agent/commit-fee",
  "/agent/commit-window/:commitId",
  "/agent/potion-balance/:characterId/:potionType/:potionTier",
  "/agent/healthcheck-write-path",
  "/economy/quote-premium",
  "/economy/estimate-epoch-roi/:characterId",
  "/leaderboard",
  "/leaderboard/character/:characterId",
  "/leaderboard/epochs/:epochId",
  "/leaderboard/claims/:characterId",
  "/market/rfqs",
  "/market/trades",
  "/market/trades/:offerId",
  "/contracts.latest.json",
  "/robots.txt",
  "/sitemap.xml",
  "/og.png",
  "/favicon.ico",
  "/"
] as const;

export const supportedWriteApiEndpoints = [
  "/agent/onboard/fund",
  "/agent/action",
  "/agent/action/:actionId",
  "/agent/preflight",
  "/agent/estimate-cost",
  "/agent/valid-actions/:characterId"
] as const;

export const supportedReadMcpTools = [
  "get_capabilities",
  "get_health",
  "get_contracts",
  "get_external",
  "get_diagnostics",
  "get_rewards",
  "quote_premium_purchase",
  "estimate_epoch_roi",
  "list_playbook_sections",
  "get_playbook_section",
  "get_agent_bootstrap",
  "get_public_rpc",
  "build_tx_intent",
  "get_world_rules",
  "list_my_characters",
  "get_commit_fee",
  "get_commit_window",
  "get_potion_balance",
  "healthcheck_write_path",
  "get_agent_state",
  "get_session_state",
  "get_leaderboard",
  "get_character_rank",
  "get_leaderboard_epoch",
  "get_claimable_epochs",
  "get_active_rfqs",
  "get_active_trade_offers",
  "get_trade_offer"
] as const;

export const supportedWriteMcpTools = [
  "request_onboard_funds",
  "onboard_player",
  "preflight_action",
  "estimate_action_cost",
  "get_valid_actions",
  "create_character",
  "start_dungeon",
  "next_room",
  "open_lootboxes_max",
  "equip_best",
  "reroll_item",
  "forge_set_piece",
  "buy_premium_lootboxes",
  "finalize_epoch",
  "claim_player",
  "claim_deployer",
  "create_trade_offer",
  "fulfill_trade_offer",
  "cancel_trade_offer",
  "cancel_expired_trade_offer",
  "create_rfq",
  "fill_rfq",
  "cancel_rfq"
] as const;
